### PR TITLE
add command line option --pw-stdin to accept password from stdin

### PR DESCRIPTION
**Pull request by jkt628**
## Description

for each database listed as a parameter read a line from stdin as the password.

## Motivation and Context

the original KeePass could accept database passwords from stdin which mitigates exposing password via environment.

## How Has This Been Tested?

i originally submitted a version this change in https://github.com/keepassx/keepassx/pull/167, 02 Jun 16, after using it personally for a few months prior.  i use this daily with a frontend script that pulls passwords from kwallet.

my environment is openSUSE Leap 42.1 using KDE.

the scope of the change is very limited and the default behavior is preserved.  nowhere else do i find reference to stdin or cin so it should not affect other areas of the code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Thanks for the PR, great work. For future reference can you further describe the use case so we can add it to documentation?

**Comment by jkt628** [comment]
i wrote a script that finds .kdbx files on my system and uses qdbus to query the password stored in kwallet.  i start keepassx with --pw-stdin and each file listed, then pipe in the associated passwords.  simple, clean, secure and i only need my kdewallet password at login.  if you want i'll stuff it into utils so others benefit.

**Comment by droidmonkey** [comment]
That would be perfect!

**Comment by jkt628** [comment]
https://github.com/keepassxreboot/keepassx/pull/55

**Pull request merged**
