### PR TITLE
Implement automatic locking when minimizing

### PR DESCRIPTION
**Pull request by JosefVitu**
## Description
This PR adds two security-related options: _Lock databases after minimizing to system tray_ and _Lock databases after minimizing to taskbar_.

The autolocking is suspended when GUI/MinimizeOnStartup is true (or to be more precise, _MainWindow::configuredMinimizeWindow()_ is left intact), as it wouldn't make much sense to lock the DB right after unlocking it.

## Motivation and Context
It enables additional workflows for using this program, and is implemented in the original KeePass as well.

## How Has This Been Tested?
Manually tested all possible combinations of the following settings:
_GUI/MinimizeOnClose
GUI/MinimizeOnStartup
GUI/MinimizeToTray
security/lockdatabasetray
security/lockdatabaseminimize_

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:
- :white_check_mark: My code follows the code style of this project.
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :white_check_mark: I have read the **CONTRIBUTING** document.
- :negative_squared_cross_mark: I have added tests to cover my changes.
- :white_check_mark: All new and existing tests passed.

Could you please review the PR and merge if deemed appropriate? Thank you.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Is there a need to distinguish between minimize and tray? I am concerned by confusing numbers/permutations of security options. KeePass suffers from this issue as it is.

This is part of a larger conversation of cleaning up config settings and making the UI more intuitive.

I'm going to try this out before I merge it to make sure it's not adding to the config soup.

**Comment by TheZ3ro** [comment]
I think @droidmonkey is right here, maybe we can make an unified option `security/lockdatabaseminimize` with text "Lock databases after minimizing the window" or "Lock databases after minimize"

**Comment by JosefVitu** [comment]
Thank you for the comments. I've been using this distinction for temporarily "hiding" (minimizing to taskbar) the window when I knew I'd need it in a few minutes again (and didn't want to type the password endlessly), and putting it away (minimizing to tray) for a long time. No idea how other people are using it, that's just how I've got used to it while using Windows and KeePass for some time.

But while I prefer having more choices with sensible and safe defaults (which most people don't change anyway), I understand your point about needless complexity.

P.S.: The system tray settings in the General tab have some superfluous hierarchy, so those should be IMHO simplified as well, but that would be probably better discussed elsewhere.

**Comment by TheZ3ro** [comment]
After testing this, I think on GNU/Linux there is no need to have 2 different option.

I'm using XFCE desktop environment and with the "Hide window to system tray when minimized" option the behaviour is the same.

@JosefVitu can you make this a single option?

Anyway right now I don't think the default options in settings are totally safe IMHO.

P.S.: With "system tray settings" you refer to Hiding on app-start and Hiding on app-exit ?

**Comment by JosefVitu** [comment]
I'm using Xfce too and have the "Hide window to system tray when minimized" option turned off just because I want to distinguish between minimizing to taskbar (no autolock) and hiding to system tray (autolock), so these two options accomplish different behaviors.

But I guess having only one option would be clearer to the users (and better than not having any), so I'll merge them and form a new habit for myself :) What should be the default value of that single option? It's _false_ now so the users wouldn't be surprised by the new behavior after upgrading, but setting it to _true_ may be a little more secure.

And yes, I was referring to those two checkboxes. Maybe I'm missing something, but I have no idea why Hiding on app start needs to depend on Hiding on exit. Then having both depend on "Hide window to system tray when minimized" is IMHO a little questionable as well, but I can somewhat understand the reasoning behind that.

**Comment by TheZ3ro** [comment]
How do you minimize to systray on XFCE? I can do this only if I have the "Hide window to system tray when minimized" option set to true, so there is no difference for me between the 2 (systray and taskbar)

IMHO the default option should be "true", but after seeing the Security tab i think the default settings prefer usability instead of security.

Anyway what about this, but I think we are overcomplicating a bit:

 * If I have the option "Hide window to system tray when minimized" set to false, 
when minimized to taskbar lock based on the "Lock when minimized" option, 
when minimized to systray ALWAYS lock.

 * If I have the option set to true, i
when minimized to taskbar or systray (doesn't matter) lock based on the "Lock when minimized" option

About the App-Exit/App-Start, this are different event in every case. SysTray/TaskBar most of the time are the same event.
We can discuss the need of an App-Start minimizing option, but it's out of this PR' scope

**Comment by JosefVitu** [comment]
@TheZ3ro By a left-click on the systray icon.

OK, let's simplify this to a single option that enables locking the databases no matter how the user minimizes/hides the window (i.e. be it either to taskbar or systray).

Will open an issue about the other thing.

**Comment by TheZ3ro** [comment]
@JosefVitu ok nice 😄

**Comment by JosefVitu** [comment]
Rebased and edited the patch as discussed.

**Pull request merged**
